### ISSUE TITLE
Error when using with module-simple-protocol-tcp

### ISSUE THREAD

**Issue by ahshum** [GeorgeFilipkin/pulsemixer#55]
Thanks for building a powerful pulse cli panel.
Recently start using simple protocol module but got error from pulsemixer.

#### Steps to reproduce

1. Create tcp sink

```shell
pactl load-module module-simple-protocol-tcp rate=48000 format=s16le channels=2 source=alsa_output.pci-0000_00_1b.0.analog-stereo.monitor record=true port=server_port listen=ip_address
```

2. Download [SimpleProtocolPlayer](https://play.google.com/store/apps/details?id=com.kaytat.simpleprotocolplayer&hl=en) and connect to the server. Once connected, pulsemixer exited with error as below.

```
Traceback (most recent call last):
  File "/usr/bin/pulsemixer", line 2054, in <module>
    main()
  File "/usr/bin/pulsemixer", line 1948, in main
    curses.wrapper(Screen(CFG.ui.color, CFG.ui.mouse).run)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/bin/pulsemixer", line 1253, in run
    self.get_data()
  File "/usr/bin/pulsemixer", line 1447, in get_data
    self.data = self.build(self.modes_data[0][0], PULSE.sink_list(), PULSE.sink_input_list())
  File "/usr/bin/pulsemixer", line 1418, in build
    bar = Bar(s[0])
  File "/usr/bin/pulsemixer", line 952, in __init__
    self.poll_data(pa, 0, 0)
  File "/usr/bin/pulsemixer", line 963, in poll_data
    media_fullname = pa.media_name.decode().replace('\n', ' ')
AttributeError: 'NoneType' object has no attribute 'decode'
```

#### Environment
```shell
$ uname -a
Linux 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64 GNU/Linux
$ pulsemixer --version
1.5.1
```

**Comment by bug5bunny3** [comment]
I'm having the same problem.
